### ISSUE TITLE
Cant flash BL602 due to `UnicodeDecodeError` in Flash Tool

### ISSUE THREAD

**Issue by berkutta** [bouffalolab/bl_iot_sdk#11]
Tried this on different Computers and with different DT-BL10 Boards. Pressed D8 and afterwards EN to enter Programming Mode before pressing Button in Flash Tool.

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4927: character maps to <undefined>`

![boufallo_bl602_flasher](https://user-images.githubusercontent.com/11159719/98422727-c9ea0700-208c-11eb-8d3b-110770aec5a9.PNG)

**Comment by YafeiJin** [comment]
@berkutta Sorry for this delay. Cause it's hard for us to reproduce this issue. So I upload one trial version, please help us verify if it's workable. Thank you very much!

https://pan.baidu.com/s/1Uwv_6F8_s4gwpKHjtVmHag 提取码: hx4x

**Comment by berkutta** [comment]
@YafeiJin Thanks, can you upload it to a different service than pan.baidu.com? I can't download from pan.baidu.com

**Comment by YafeiJin** [comment]
@berkutta Your email?

**Comment by berkutta** [comment]
@YafeiJin info@benjaminmarty.ch

**Comment by berkutta** [comment]
Version v1.4.5.1 works for me. I uploaded the file I got from @YafeiJin to mega.nz so others can download it easily: https://mega.nz/file/h9U0HZoZ#JZdBFhXwwLcuVAW0uK91TRav2iP2dagKSlLD22jE_9g

Please also update the Repository so others won't face this issue.

**Comment by YafeiJin** [comment]
Thanks for your help.
We will update this after some regular testing.
