### ISSUE TITLE
BL602的Linux环境搭建？

### ISSUE THREAD

**Issue by giting-666** [bouffalolab/bl_iot_sdk#15]
你好，官方：
         请问是否有详细的BL602的Linux环境搭建教程，我看了SDK里的《https://github.com/bouffalolab/bl_iot_sdk/tree/master/docs/html/Developer_Environment》只是有一些组件的install，没有看到相关交叉编译的工具链以及PATH的设置，请问方便提供详细环境搭建资料吗？
![image](https://user-images.githubusercontent.com/45549027/98761081-a10c9d80-240f-11eb-9b24-a1b3ceab93bd.png)

**Comment by giting-666** [comment]
@YafeiJin @bouffalolab2020

**Comment by YafeiJin** [comment]
SDK includes the toolchains for Linux/Macos/Windows, and compiling framework will work with this default path.  No other setting required.

**Comment by giting-666** [comment]
我看SDK里没有说明BLE可同时连接的最多连接数量，就是支持一主几从？

**Comment by YafeiJin** [comment]
Currently, it can support two ble connections. Two masters/two slaver/one master+ one slave
