### ISSUE TITLE
Please provide Upload tool for Linux

### ISSUE THREAD

**Issue by oeidfhlsk** [bouffalolab/bl_iot_sdk#16]
Hi there,
I already got some DEV-Boards but cant seem to find an upload tool for linux machines. I cant even get  BlDevCube.exe from this repo running in a Win10 VM, because it seems this is not the right file taken from Pythoninstaller. Another version of BlDevCube i could find on the Internet is abuout 10 times bigger filesize-wise and works flawless. However, i would like to upload from native linux terminal.

![BlDevCube_error](https://user-images.githubusercontent.com/26968485/99184317-38406080-2742-11eb-89a8-8425ec6158be.PNG)

**Comment by YafeiJin** [comment]
Could you please provide the error info in Linux? os info also needed, thanks

**Comment by oeidfhlsk** [comment]
Linux upload tool is simply missing from tools folder. Or am I missing something?

**Comment by gamelaster** [comment]
Hi @oeidfhlsk , there you go:
https://pine64.gami.ee/bl602/BLFlashEnv

**Comment by YafeiJin** [comment]
Really sorry for missing uploading the linux version, and We will correct soon.
@gamelaster Thanks.

**Comment by oeidfhlsk** [comment]
@gamelaster Thanks. I could flash upload now for the first time.

**Comment by gamelaster** [comment]
@oeidfhlsk probably dumb question, but do you have installed Python 3.7?

**Comment by oeidfhlsk** [comment]
I did, but i just came up with the nex missing dll. Probably this is the solution, upload 

> output from dist/{filename}, rather then build/{filename}
(https://stackoverflow.com/questions/19225132/pyinstaller-not-working-on-simple-helloworld-program)

**Comment by YafeiJin** [comment]
@oeidfhlsk I will close this issue for the open source tools is ready now. https://github.com/bouffalolab/BLOpenFlasher
