### ISSUE TITLE
OpenOCD.exe miss depedencies

### ISSUE THREAD

**Issue by gamelaster** [bouffalolab/bl_iot_sdk#22]
Hi,

I tried to use OpenOCD.exe in Flasher, sadly, it miss following libraries: `libftdi1.dll`, `libusb-0-1-4.dll` and `libusb1.0.dll`.

I tried latest OpenOCD, it actually works, but it shows "WaitCmd" is missing, so maybe yours OpenOCD is modified?

**Comment by YafeiJin** [comment]
What's your debugger device? Please refer to https://github.com/bouffalolab/bl_docs/tree/main/BL602_Openocd%26GDB
OpenOCD is the standard version.

**Comment by gamelaster** [comment]
Hi Yafei,

The JTAG works OK for me, just [openocd.exe](https://github.com/bouffalolab/bl_iot_sdk/blob/master/tools/flash_tool/openocd.exe) in this repository don't work. (it miss following libraries: libftdi1.dll, libusb-0-1-4.dll and libusb1.0.dll). Else it works good, flashing through BLCubeEnv.exe but also debugging.

**Comment by YafeiJin** [comment]
Uploaded these libraries:  libftdi1.dll, libusb-0-1-4.dll and libusb1.0.dll.
