### ISSUE TITLE
Chinese doc is down

### ISSUE THREAD

**Issue by chuangzhu** [bouffalolab/bl_iot_sdk#51]
https://bouffalolab.github.io/bl_iot_sdk/ is down

![Screenshot_20210424_172715](https://user-images.githubusercontent.com/31200881/115954216-53e63900-a522-11eb-924a-414d8ab49742.png)

**Comment by balanceTWK** [comment]
直接下载下来，打开 bl_iot_sdk/docs/html/index.html 就是中文的。
