### ISSUE TITLE
请问有 裸机工程 么？

### ISSUE THREAD

**Issue by balanceTWK** [bouffalolab/bl_iot_sdk#53]

**Comment by gamelaster** [comment]
https://github.com/bouffalolab/bl_iot_sdk/tree/master/customer_app/sdk_app_helloworld

**Comment by balanceTWK** [comment]
> https://github.com/bouffalolab/bl_iot_sdk/tree/master/customer_app/sdk_app_helloworld

Thanks for your reply! I mean is there a No RTOS project? I want to port to RT-Thread.

**Comment by gamelaster** [comment]
@balanceTWK This example I sent you doesn't use RTOS. It includes `FreeRTOS.h`, but it should work even without it (after some easy modifications).

**Comment by balanceTWK** [comment]
> @balanceTWK This example I sent you doesn't use RTOS. It includes `FreeRTOS.h`, but it should work even without it (after some easy modifications).

Thanks again for your reply.
