### ISSUE TITLE
How to build Zigbee sample firmware?

### ISSUE THREAD

**Issue by tomasz-s** [bouffalolab/bl_iot_sdk#60]
I bought some XT-ZB1 DevKit boards and want to run some Zigbee on it.
Basic samples compiles ok but Zigbee sample cannot find components.
but when I trying "./genzsed" compilation failed
 
 /root/bl_iot_sdk-master/components/network/zigbee/zigbee_def.mk: No such file or directory

**Comment by shchen-Lab** [comment]
> 
BL702 zigbee SDK is only avaliable when NDA is signed. Please contact our sales team.

**Comment by turboJo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by joshOberhaus** [comment]
> I bought some XT-ZB1 DevKit boards and want to run some Zigbee on it. Basic samples compiles ok but Zigbee sample cannot find components. but when I trying "./genzsed" compilation failed
> 
> /root/bl_iot_sdk-master/components/network/zigbee/zigbee_def.mk: No such file or directory

Did you end up getting access? I've been requesting the NDA for weeks.
