### ISSUE TITLE
Some issues about compiling 

### ISSUE THREAD

**Issue by Yangff** [bouffalolab/bl_iot_sdk#7]
1. For any app use headers from hal, `CONFIG_CHIP_NAME=BL602` needs to be exported so the compile script can find the correct components.

2. By default, it links with link script flash.ld which does not have informaiton to link against wifi lib. To compile wifi, the `flash_rom.ld` needs to be selected with `CONFIG_LINK_ROM=1`

**Comment by YafeiJin** [comment]
Q1: With the define, SDK is able to support different chip.
Q2: wifi lib is controlled by the component name,  bl602_wifi, in the Makefile. CONFIG_LINK_ROM is used to link the rom code, and ignore flash.ld please.
