### ISSUE TITLE
build fail on Ubuntu 18.04 due to glic version requirement

### ISSUE THREAD

**Issue by bloom5** [bouffalolab/bl_iot_sdk#9]
Error loading Python lib '/tmp/_MEILQJ82s/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEILQJ82s/libpython3.7m.so.1.0)

**Comment by YafeiJin** [comment]
@bloom5 Please temporally remove the following line from make_scripts_riscv/project.mk to work around this error. 
@cd $(BL60X_SDK_PATH)/image_conf; ./flash_build $(PROJECT_NAME) $(CONFIG_CHIP_NAME)
then use BLDevCube.exe to burn the flash.

**Comment by bloom5** [comment]
> 
> 
> @bloom5 Please temporally remove the following line from make_scripts_riscv/project.mk to work around this error.
> @cd $(BL60X_SDK_PATH)/image_conf; ./flash_build $(PROJECT_NAME) $(CONFIG_CHIP_NAME)
> then use BLDevCube.exe to burn the flash.

Thanks! It works.
